name: Verify

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

#    - uses: actions/cache@v3
#      with:
#        path: ~/.cache/pip
#        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
#        restore-keys: |
#          ${{ runner.os }}-pip-

    - name: Set up Python "3.10"
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt
        sudo apt install -y --no-install-recommends iverilog
    - name: Verify with cocotb & icarus
      run: |
        pytest -v --workers 10 tests/test_cic_d.py
